package com.mycompany.projeto.individual;
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author adria
 */
public class Projeto1_Monitoramento extends javax.swing.JFrame {
    
Integer minCPU = 101;
Integer maxCPU = 0;
Double mediaCPU = 0.0;    

Integer minDisco = 101;
Integer maxDisco = 0;
Double mediaDisco = 0.0; 

Integer minMemoria = 101;
Integer maxMemoria = 0;
Double  mediaMemoria = 0.0; 

Integer contador = 0;

 /**
     * Creates new form Projeto1_Monitoramento
     */
    public Projeto1_Monitoramento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLeitura = new javax.swing.JButton();
        lblCPU = new javax.swing.JLabel();
        lblDisco = new javax.swing.JLabel();
        lblMemoria = new javax.swing.JLabel();
        pgbCPU = new javax.swing.JProgressBar();
        pgbDisco = new javax.swing.JProgressBar();
        pgbMemoria = new javax.swing.JProgressBar();
        lblAtualDisco = new javax.swing.JLabel();
        lblMinDisco = new javax.swing.JLabel();
        lblMaxDisco = new javax.swing.JLabel();
        lblMediaDisco = new javax.swing.JLabel();
        lblMaxCPU = new javax.swing.JLabel();
        lblMediaCPU = new javax.swing.JLabel();
        lblAtualCPU = new javax.swing.JLabel();
        lblMinCPU = new javax.swing.JLabel();
        lblMaxMemoria = new javax.swing.JLabel();
        lblMediaMemoria = new javax.swing.JLabel();
        lblAtualMemoria = new javax.swing.JLabel();
        lblMinMemoria = new javax.swing.JLabel();
        lblMinMem = new javax.swing.JLabel();
        lblMaxMem = new javax.swing.JLabel();
        lblMaxDisc = new javax.swing.JLabel();
        lblMinDisc = new javax.swing.JLabel();
        lblMaxCP = new javax.swing.JLabel();
        lblMinCP = new javax.swing.JLabel();
        lblAtualCpu = new javax.swing.JLabel();
        lblMinCpu = new javax.swing.JLabel();
        lblMaxCpu = new javax.swing.JLabel();
        lblMediaCpu = new javax.swing.JLabel();
        lblAtualdisco = new javax.swing.JLabel();
        lblMindisco = new javax.swing.JLabel();
        lblMaxdisco = new javax.swing.JLabel();
        lblMediadisco = new javax.swing.JLabel();
        lblatualMemoria = new javax.swing.JLabel();
        lblMinMemoriA = new javax.swing.JLabel();
        lblMaxMemoriA = new javax.swing.JLabel();
        lblMediamemoria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLeitura.setText("Fazer leitura de dados");
        btnLeitura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeituraActionPerformed(evt);
            }
        });

        lblCPU.setText("CPU");

        lblDisco.setText("Disco");

        lblMemoria.setText("Memória");

        lblAtualDisco.setText("Atual");

        lblMinDisco.setText("Min");

        lblMaxDisco.setText("Max");

        lblMediaDisco.setText("Média");

        lblMaxCPU.setText("Max");

        lblMediaCPU.setText("Média");

        lblAtualCPU.setText("Atual");

        lblMinCPU.setText("Min");

        lblMaxMemoria.setText("Max");

        lblMediaMemoria.setText("Média");

        lblAtualMemoria.setText("Atual");

        lblMinMemoria.setText("Min");

        lblMinMem.setText("0");

        lblMaxMem.setText("100");

        lblMaxDisc.setText("100");

        lblMinDisc.setText("0");

        lblMaxCP.setText("100");

        lblMinCP.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCPU)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMinCP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMaxCP))
                            .addComponent(pgbCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAtualCPU)
                            .addComponent(lblMinCPU)
                            .addComponent(lblMaxCPU)
                            .addComponent(lblMediaCPU))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMediaCpu)
                            .addComponent(lblMaxCpu)
                            .addComponent(lblMinCpu)
                            .addComponent(lblAtualCpu))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(lblDisco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMinDisc)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblMaxDisc)
                        .addComponent(pgbDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMinDisco)
                                    .addComponent(lblAtualDisco)
                                    .addComponent(lblMaxDisco))
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblMediaDisco)
                                .addGap(45, 45, 45)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMediadisco)
                            .addComponent(lblMaxdisco)
                            .addComponent(lblMindisco)
                            .addComponent(lblAtualdisco))))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(pgbMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblAtualMemoria)
                                            .addComponent(lblMediaMemoria)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblMaxMemoria)
                                                    .addComponent(lblMinMemoria))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblMediamemoria)
                                            .addComponent(lblMaxMemoriA)
                                            .addComponent(lblMinMemoriA)
                                            .addComponent(lblatualMemoria)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblMinMem)
                                        .addGap(87, 87, 87)
                                        .addComponent(lblMaxMem)))
                                .addGap(8, 8, 8))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMemoria)
                        .addGap(141, 141, 141)))
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(btnLeitura, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCPU)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pgbCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMinCP)
                                .addComponent(lblMaxCP))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAtualCPU)
                                .addComponent(lblAtualCpu))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblMinCPU)
                                .addComponent(lblMinCpu))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblMaxCPU)
                                .addComponent(lblMaxCpu))
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblMediaCPU)
                                .addComponent(lblMediaCpu)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblMemoria))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pgbMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMinMem)
                                    .addComponent(lblMaxMem))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblatualMemoria)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblMinMemoriA))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblAtualDisco)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblMinDisco)
                                                .addGap(27, 27, 27)
                                                .addComponent(lblMaxDisco)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblMediaDisco))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblAtualdisco)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblMindisco)
                                                .addGap(27, 27, 27)
                                                .addComponent(lblMaxdisco)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblMediadisco)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblAtualMemoria)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblMinMemoria)
                                            .addGap(24, 24, 24)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblMaxMemoria)
                                                        .addComponent(lblMaxMemoriA))
                                                    .addGap(43, 43, 43))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(lblMediaMemoria)
                                                    .addComponent(lblMediamemoria)))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblDisco))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pgbDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblMinDisc))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMaxDisc)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btnLeitura)
                .addGap(135, 135, 135))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeituraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeituraActionPerformed
    Random aleatorio = new Random();
    
    contador ++  ;
    
    Integer cpu = aleatorio.nextInt(101);
    Integer disco = aleatorio.nextInt(101);
    Integer memoria = aleatorio.nextInt(101);
    
    pgbCPU.setValue(cpu);
    pgbDisco.setValue(disco);
    pgbMemoria.setValue(memoria);
    
    if (cpu < minCPU ) {
     minCPU = cpu; 
      lblMinCpu.setText(String.valueOf(minCPU));
    }//GEN-LAST:event_btnLeituraActionPerformed

    if (cpu > maxCPU ) {
     maxCPU = cpu;
     lblMaxCpu.setText(String.valueOf(maxCPU));
        }
   
    if (disco < minDisco ) {
     minDisco = disco; 
     lblMindisco.setText(String.valueOf(minDisco));
    }
    
    if (disco > maxDisco ) {
     maxDisco = disco; 
      lblMaxdisco.setText(String.valueOf(maxDisco));
    }
  
    if (memoria < minMemoria ) {
     minMemoria = disco; 
       lblMinMemoriA.setText(String.valueOf(minMemoria));
    }
    
    if (memoria > maxMemoria ) {
     maxMemoria  = memoria ; 
     lblMaxMemoriA.setText(String.valueOf(maxMemoria));
    }
   
    mediaCPU = (mediaCPU + cpu);
    mediaDisco = (mediaDisco + disco);
    mediaMemoria = (mediaMemoria + memoria);
    
    Double calculoMediaCPU = mediaCPU / contador;
    Double calculoMediaDisco = mediaDisco / contador;
    Double calculoMediaMemoria = mediaMemoria / contador; 
    
    lblAtualCpu.setText(String.valueOf(cpu));
    lblAtualdisco.setText(String.valueOf(disco));
    lblatualMemoria.setText(String.valueOf(memoria));
    
   
    lblMediaCpu.setText(String.valueOf(calculoMediaCPU));
    lblMediadisco.setText(String.valueOf(calculoMediaDisco));
    lblMediamemoria.setText(String.valueOf(calculoMediaMemoria));
    
       }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Projeto1_Monitoramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Projeto1_Monitoramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Projeto1_Monitoramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Projeto1_Monitoramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Projeto1_Monitoramento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLeitura;
    private javax.swing.JLabel lblAtualCPU;
    private javax.swing.JLabel lblAtualCpu;
    private javax.swing.JLabel lblAtualDisco;
    private javax.swing.JLabel lblAtualMemoria;
    private javax.swing.JLabel lblAtualdisco;
    private javax.swing.JLabel lblCPU;
    private javax.swing.JLabel lblDisco;
    private javax.swing.JLabel lblMaxCP;
    private javax.swing.JLabel lblMaxCPU;
    private javax.swing.JLabel lblMaxCpu;
    private javax.swing.JLabel lblMaxDisc;
    private javax.swing.JLabel lblMaxDisco;
    private javax.swing.JLabel lblMaxMem;
    private javax.swing.JLabel lblMaxMemoriA;
    private javax.swing.JLabel lblMaxMemoria;
    private javax.swing.JLabel lblMaxdisco;
    private javax.swing.JLabel lblMediaCPU;
    private javax.swing.JLabel lblMediaCpu;
    private javax.swing.JLabel lblMediaDisco;
    private javax.swing.JLabel lblMediaMemoria;
    private javax.swing.JLabel lblMediadisco;
    private javax.swing.JLabel lblMediamemoria;
    private javax.swing.JLabel lblMemoria;
    private javax.swing.JLabel lblMinCP;
    private javax.swing.JLabel lblMinCPU;
    private javax.swing.JLabel lblMinCpu;
    private javax.swing.JLabel lblMinDisc;
    private javax.swing.JLabel lblMinDisco;
    private javax.swing.JLabel lblMinMem;
    private javax.swing.JLabel lblMinMemoriA;
    private javax.swing.JLabel lblMinMemoria;
    private javax.swing.JLabel lblMindisco;
    private javax.swing.JLabel lblatualMemoria;
    private javax.swing.JProgressBar pgbCPU;
    private javax.swing.JProgressBar pgbDisco;
    private javax.swing.JProgressBar pgbMemoria;
    // End of variables declaration//GEN-END:variables
}
